%Construct a database of the periodic table (use a vector for each different field: symbolic name, atomic number, atomic weight, electronagativity and its description .
%Provide a lookup to return all information of an element for a specific input criterion (such as the symbolic name).
function PeriodicTable1(a)
Elements = {"Hydrogen", "Lithium", "Sodium", "Potassium", "Rubidium", "Caesium", "Francium", ...
    "Beryllium", "Magnesium", "Calcium", "Strontium", "Barium", "Radium", ...
    "Boron", "Aluminum", "Gallium", "Indium", "Thallium", "Nihonium", ...
    "Carbon", "Silicon", "Germanium", "Tin", "Lead", "Flerovium", ...
    "Nitrogen", "Phosphorous", "Arsenic", "Antimony", "Bismuth", "Moscovium", ...
    "Oxygen", "Sulfur", "Selenium", "Tellurium", "Polonium", "Livemorium", ...
    "Fluorine", "Chlorine", "Bromine", "Iodine", "Astatine", "Tennessine", ...
    "Helium", "Neon", "Argon", "Kripton", "Xenon", "Radon", "Oganesson", ...
    "Scandium", "Yttrium", ...
    "Titanium", "Zirconium", "Hafnium", "Rutherfordium", ...
    "Vanadium", "Niobium", "Tantalum", "Dubnium", ...
    "Chromium", "Molybdenum", "Tungsten", "Seaborgium", ...
    "Manganese", "Technetium", "Rhenium", "Bohrium", ...
    "Iron", "Ruthenium", "Osmium", "Hassium", ...
    "Cobalt", "Rhodium", "Iridium", "Meitnerium", ...
    "Nickel", "Palladium", "Platinum", "Darmstadtium", ...
    "Copper", "Silver", "Gold", "Roentgenium", ...
    "Zinc", "Cadmium", "Mercury", "Copemicium", ...
    "Lanthanum", "Cerium", "Praseodymium", "Neodymium", "Promethium", "Samarium", "Europium", "Gadolinium", "Terbium", "Dysprosium", "Holmium", "Erbium", "Thulium", "Ytterbium", "Lutetium", ...
    "Actinium", "Thorium", "Protactinium", "Uranium", "Neptunium", "Plutonium", "Americium", "Curium", "Berkelium", "Califomium", "Einsteinium", "Fermium", "Mendelevium", "Nobelium", "Lawrencium";
    "H", "Li", "Na", "K", "Rb", "Cs", "Fr", ... %ElementsSymbol.
    "Be", "Mg", "Ca", "Sr", "Ba", "Ra", ...
    "B", "Al", "Ga", "In", "Tl", "Nh", ...
    "C", "Si", "Ge", "Sn", "Pb", "Fl", ...
    "N", "P", "As", "Sb", "Bi", "Mc", ...
    "O", "S", "Se", "Te", "Po", "Lv", ...
    "F", "Cl", "Br", "I", "At", "Ts",...
    "He", "Ne", "Ar", "Kr", "Xe", "Rn", "Og", ...
    "Sc", "Y", ...
    "Ti", "Zr", "Hf", "Rf", ...
    "V", "Nb", "Ta", "Bd", ...
    "Cr", "Mo", "W", "Sg", ...
    "Mn", "Tc", "Re", "Bh", ...
    "Fe", "Ru", "Os", "Hs", ...
    "Co", "Rh", "Ir", "Mt", ...
    "Ni", "Pd", "Pt", "Ds", ...
    "Cu", "Ag", "Au", "Rg", ...
    "Zn", "Cd", "Hg", "Cn", ...
    "La", "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb", "Lu", ...
    "Ac", "Th", "Pa", "U", "Np", "Pu", "Am", "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr";
    1, 3, 11, 19, 37, 55, 87,... %AtomicNumber
    4, 12, 20, 38, 56, 88, ...
    5, 13, 31, 49, 81, 113, ...
    6, 14, 32, 50, 82, 114, ...
    7, 15, 33, 51, 83, 115, ...
    8, 16, 34, 52, 84, 116, ...
    9, 17, 35, 53, 85, 117, ...
    2, 10, 18, 36, 54, 86, 118,...
    21, 39,...
    22, 40, 72, 104,...
    23, 41, 73, 105, ...
    24, 42, 74, 106, ...
    25, 43, 75, 107, ...
    26, 44, 76, 108, ...
    27, 45, 77, 109, ...
    28, 46, 78, 110, ...
    29, 47, 79, 111,...
    30, 48, 80, 112,...
    57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, ...
    89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103;
    1, 7, 23, 39, 85.5, 132.9, 232, ... %Atomic mass
    9, 24, 40, 87.6, 137.3, 226, ...
    10.8, 27, 70, 114.8, 204.3, 286.2, ...
    12, 28, 72.6, 118.7, 207, 290.2, ...
    14, 31, 75, 121.8, 209, 290.2, ...
    16, 32, 79, 127.6, 209, 293.2, ...
    19, 36, 79.9, 126.9, 210, 294.2, ...
    4, 20.2, 39.9, 83.8, 131.3, 222, 295.2, ...
    45, 89, ...
    47.9, 91.2, 178.5, 267.1, ...
    50.9, 92.9, 180.9, 268.1, ...
    52, 96, 180.9, 268.1, ...
    52, 96, 183.8, 269.1, ...
    55, 96.9, 186.2, 270.1, ...
    55.8, 203, 192.2, 277.1, ...
    58.7, 106.4, 195.1, 282.2, ...
    63.6, 107.9, 197, 282.2, ...
    65.4, 112.4, 200.6, 286.2, ...
    138.9, 140.1, 141, 144.2, 144.9, 150.4, 152, 157.2, 158.9, 162.5, 164.9, 167.3, 168.9, 173.1, 175, ...
    227, 232, 231, 238, 237, 244, 243, 247.1, 247.1, 251.1, 252.1, 257.1, 258.1, 259.1, 266.1;
    2.2, 0.98, 0.93, 0.82, 0.82, 0.78, 0.7, ... %Electronegativity
    1.57, 1.31, 1.00, 0.95, 0.89, 0.89, ...
    2.04, 1.61, 1.81, 1.78, 1.62, NaN, ...
    2.55, 1.90, 2.01, 1.96, 2.33, NaN, ...
    3.04, 2.19, 2.18, 2.05, 2.02, NaN, ...
    3.44, 2.58, 2.55, 2.1, 2.0, NaN, ...
    3.98, 3.18, 2.96, 2.66, 2.2, NaN, ...
    NaN, NaN, NaN, 3, 2.6, NaN, NaN, ...
    1.36, 1.22, ...
    1.54, 1.33, 1.3, NaN, ...
    1.63, 1.6, 1.5, NaN, ...
    1.66, 2.16, 2.36, NaN, ...
    1.55, 1.9, 1.9, NaN, ...
    1.83, 2.2, 2.2, NaN, ...
    1.88, 2.28, 2.2, NaN, ...
    1.91, 2.2, 2.28, NaN, ...
    1.9, 1.93, 2.54, NaN, ...
    1.65, 1.69, 2, NaN ...
    1.1, 1.12, 1.13, 1.14, 1.13, 1.17, 1.2, 1.2, 1.1, 1.22, 1.23, 1.24, 1.25, 1.1, 1.27, ...
    1.1, 1.3, 1.5, 1.38, 1.36, 1.28, 1.13, 1.28, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.291;
    "Hydrogen is an explosive gas and also the lightest element", ... %Description
    "Under standard conditions, Lithium is the lightest metal and is soft and reactive.", ...
    "c", ...
    "Potassium is a soft metal and is reactive.", ...
    "Rubidium is a soft metal that is reactive.", ...
    "Caesium (Cesium) is a reactive soft metal withthe the largest stable atoms.", ...
    "Francium is a radioactive and short-lived element with atoms larger than cesium.", ...
    "Beryllium is a lightweight metal.", ...
    "Magnesium is a lightweight metal.", ...
    "Calcium is a soft metal.", ...
    "Strontium is a soft metal.", ...
    "Barium is a soft metal that absorbs X-rays.", ...
    "c", ...
    "Boron is a powdery, black solid.", ...
    "Aluminum is a lightweight non-corroding metal.", ...
    "Gallium is a soft metal that has a low melting point.", ...
    "Indium is a soft metal.", ...
    "Thallium is a toxic soft metal.", ...
    "c", ...
    "There are a number of pure forms of this element, including graphite, diamond, fullerenes, and graphene. The nano-forms, fullerenes, and graphene appear black or dark brown, soot-like powders.", ...
    "Silicon is a hard metalloid.", ...
    "Germanium is a brittle metalloid.", ...
    "Tin is a non-corroding soft metal.", ...
    "Lead is a dense, soft, non-corroding toxic metal.", ...
    "c", ...
    "Nitrogen is a colorless gas.", ...
    "Phosphorus is a glowing white waxy solid.", ...
    "Arsenic is a brittle metalloid.", ...
    "Antimony is a brittle metalloid.", ...
    "Bismuth is a brittle metal with a low melting point.", ...
    "c", ...
    "Oxygen is a colorless gas.", ...
    "Sulfur is a brittle yellow solid.", ...
    "Selenium is a brittle gray solid.", ...
    "Tellurium is a brittle metalloid.", ...
    "b", ...
    "c", ...
    "Fluorine is a yellowish poison gas and the most reactive element.", ...
    "Chlorine is a greenish poisonous gas.", ...
    "Bromine is a dark red liquid.", ...
    "Iodine is a violet-black solid.", ...
    "Astatine is a radioactive element that is short-lived.", ...
    "c", ...
    "Helium is an inert gas and the second-lightest element.", ...
    "Neon is an inert gas.", ...
    "Argon is an inert gas.", ...
    "Krypton is an inert gas", ...
    "Xenon is an inert gas", ...
    "Radon is a radioactive gas that is short-lived.", ...
    "Oganesson is a radioactive element that is short-lived. It is the heaviest element known to man.", ...
    "Scandium is a soft, lightweight metal.", ...
    "Yttrium is a soft metal.", ...
    "Titanium is the strongest lightweight metal and is heat-resistant.", ...
    "Zirconium is a non-corroding neutron-resistant metal.", ...
    "Hafnium is a non-corroding metal that absorbs neutrons.", ...
    "Hafnium is a non-corroding metal that absorbs neutrons.", ...
    "Vanadium is a hard metal.", ...
    "Niobium is a non-corroding metal with a high melting point.", ...
    "Tantalum is a high-melting-point non-corroding metal.", ...
    "c", ...
    "Chromium is a hard, shiny metal.", ...
    "Molybdenum is a high-melting-point metal.", ...
    "Tungsten is the highest-melting-point dense metal.", ...
    "c", ...
    "Manganese is a hard metal.", ...
    "b", ...
    "Rhenium is a high-melting-point dense metal.", ...
    "c", ...
    "Iron is a medium-hard metal and has magnetic properties.", ...
    "c", ...
    "Osmium is a non-corroding high-melting-point hard metal and is the densest element.", ...
    "c", ...
    "Cobalt is a hard metal and is magnetic.", ...
    "Rhodium is a non-corroding hard, shiny metal.", ...
    "Iridium is a non-corroding hard metal and is also the densest element (same as Os).", ...
    "c", ...
    "Nickel is a medium-hard metal and is magnetic.", ...
    "Palladium is a non-corroding hard metal that readily absorbs hydrogen.", ...
    "Platinum is a non-corroding dense metal.", ...
    "c", ...
    "Copper is a colored metal that conducts heat and electricity well.", ...
    "Silver is a soft, shiny metal that is the best electrical conductor.", ...
    "Gold is the most malleable element, and is a dense non-tarnishing colored metal.", ...
    "c", ...
    "Zinc is a non-corroding metal.", ...
    "Cadmium is a non-corroding soft metal that is toxic.", ...
    "Mercury is a liquid metal and is toxic.", ...
    "c", ...
    "a", "a", "a", "a", "b", "a", "a", "Gadolinium is a soft metal that is the best neutron absorber and is magnetic.", "a", "a", "a", "a", "a", "a", "Lutetium is a soft metal and is the densest and hardest rare earth metal.",  ...
    "b", "b", "b", "b", "b", "b", "b", "b", "b", "b", "c", "c", "c", "c", "c"};
for i = 1:118
    if strcmp(Elements{2,i}, a)
        fprintf("---------------------------------------------------------------------------------------------------------------\n");
        fprintf('Element: <strong>%s</strong> \n', Elements{1,i});
        fprintf("Symbol: %s\n", Elements{2, i});
        fprintf("Atomic number: %d.\n", Elements{3, i});
        fprintf("Atomic weight: %.1fu.\n", Elements{4, i});
        if ~isnan(Elements{5, i})
            fprintf("Electronegativity: %.2f. \n",Elements{5, i});
        else
            fprintf("There's no data found for negativity of element %s", Elements{1, i });
        end
        fprintf("Description: ");
        switch Elements{6, i}
            case "c"
                fprintf("%s is a radioactive element that is short-lived.\n", Elements{1, i });
            case "b"
                fprintf("%s is a radioactive element that is long-lived.\n", Elements{1, i });
            case "a"
                fprintf("%s is a soft metal\n", Elements{1, i});
            otherwise
                fprintf("%s\n", Elements{6, i});
        end
        fprintf("Group: ");
        switch i
            case 1
                fprintf("IA\n");
            case num2cell(2:7)
                fprintf("IA and also an alkali metal.\n");
            case num2cell(8:13)
                fprintf("IIA and also an alkaline metal.\n");
            case num2cell(14:19)
                fprintf("IIIA.\n");
            case num2cell(20:25)
                fprintf("IVA.\n");
            case num2cell(26:31)
                fprintf("VA.\n");
            case num2cell(32:37)
                fprintf("VIA.\n");
            case num2cell(38:43)
                fprintf("VIIA.\n");
            case num2cell(44:50)
                fprintf("VIIIA and also a noble gases.\n" );
            case num2cell(51:52)
                fprintf("IIIB.\n");
            case num2cell(53:56)
                fprintf("IVB.\n");
            case num2cell(57:60)
                fprintf("VB.\n");
            case num2cell(61:64)
                fprintf("VIB.\n");
            case num2cell(65:68)
                fprintf("VIIB.\n");
            case num2cell(69:72)
                fprintf("VIIIB.\n");
            case num2cell(73:76)
                fprintf("IB.\n");
            case num2cell(77:80)
                fprintf("IIB.\n");
            case num2cell(81:95)
                fprintf("Lanthanide Series.\n");
            otherwise
                fprintf("Actinide Series.\n");
        end
        fprintf("Period:"); 
        switch Elements{3, i}
            case num2cell(1:2)
                fprintf("1.\n"); 
            case num2cell(3:10)
                fprintf("2.\n"); 
            case num2cell(11:18)
                fprintf("3.\n"); 
            case num2cell(19:36)
                fprintf("4.\n"); 
            case num2cell(37:54)
                fprintf("5.\n"); 
            case num2cell(55:86)
                fprintf("6.\n"); 
            otherwise
                fprintf("7.\n"); 
        end
    end
end
end
